### ISSUE TITLE
Incompatible with latest talker_flutter

### ISSUE THREAD

**Issue by yauhenipakala** [Frezyx/debug_friend#13]
Your package looks useful but can't be used:

**Steps:**
1. Create empty flutter project
2. Add `talker_flutter: ^4.0.0` package
3. Run `flutter pub get` - OK
4. Add `debug_friend: ^1.0.0` package
5. Run `flutter pub get` - Error

**Actual:**

Error:
```
flutter pub get --no-example
Resolving dependencies...
Because test_app depends on debug_friend ^1.0.0 which depends on talker_flutter ^1.6.0, talker_flutter ^1.6.0 is required.
So, because test_app depends on talker_flutter ^4.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on debug_friend: flutter pub add debug_friend:^0.1.0
exit code 1
```

--- 
Flutter v3.16.9

**Comment by Frezyx** [comment]
Hello @wcoder ! 
New version **1.0.1** with talker update currently available at pub.dev [debug_friend](https://pub.dev/packages/debug_friend)
